Code cleanup of tests of gui elements.
Cosmetic cleanup at this time. Will test later on Linux system.

Items left to address:
test/test_asyncjobs.py:25:1: F401 'pysheng.yieldfrom.supergenerator'
imported but unused
test/test_asyncjobs.py:25:1: F401 'pysheng.yieldfrom._from' imported but
unused
test/test_asyncjobs.py:224:1: F811 redefinition of unused
'threaded_task' from line 179
test/test_asyncjobs.py:236:1: F811 redefinition of unused
'TestThreadedTask' from line 188